### ISSUE TITLE
logger broke after empty message

### ISSUE THREAD

**Issue by centralhardware** [idelsink/b-log#7]
if i execute code 

`INFO ""
`
after this logging, neither the console nor the file works

**Comment by idelsink** [comment]
This is 'by design'.  Currently it checks if the variable with the message is empty and when it is, it waits for stdin. The string `""` is an empty string and the `-z` option checks for an empty string. 

See: https://github.com/idelsink/b-log/blob/master/b-log.sh#L313

Thanks for the issue tho, but I'm not sure if this should be 'fixed'.

**Comment by centralhardware** [comment]
In any case, this should be reflected in the readm, and ideally it would be possible to show warning when using
